### ISSUE TITLE
error when running cli

### ISSUE THREAD

**Issue by DeRuiterIndustrieleAutomatisering** [biblibre/kanboard-plugin-StarredProjects#1]
When I start cli in the cronjob I get the error "[critical] StarredProjects: Unable to migrate schema for the plugin: StarredProjects => SQLSTATE[HY000]: General error: 1 near "AUTO_INCREMENT": syntax error".

If this plugin is not installed I don't get any errors.

**Comment by jajm** [comment]
I'm assuming you are using sqlite. I just pushed https://github.com/biblibre/kanboard-plugin-StarredProjects/commit/b628cb106297cb345c2f48d076c403f88f6e8020. Can you confirm it fixes the problem ?

**Comment by ludertal** [comment]
Hello,

had the same error (SQLSTATE[HY000]: General error: 1 near "AUTO_INCREMENT": syntax error".) while installing the plugin. I took the master commit version and the error is now gone, but I don't understand how to use this plugin ?

How does it works, can you add some screenshots please ? where is the button or action supposed to appear ?

FYI, I installed the plugin manually  > upload .zip > renamed the folder StarredProjects. Is there something other to set ?

Regards

**Comment by jajm** [comment]
> How does it works, can you add some screenshots please ? where is the button or action supposed to appear ?

The plugin adds a little star next to project name in overview page. Click on stars to mark projects as favorite and refresh the page, they will appear on top of the overview page.

**Comment by ludertal** [comment]
Sorry, I have nothing on screen (no star to click). The Sqlite error is gone however with v 0.1.1

**Comment by jajm** [comment]
> Sorry, I have nothing on screen (no star to click)

Maybe you have another plugin which also override the template `dashboard/overview.php` ?

**Comment by ludertal** [comment]
I tried on an empty instance, I see the star now (so it's maybe a plugin override issue as you say), but I cannot click on it, nothing happens, the star stay empty (outlined in black, white inside)

**Comment by jajm** [comment]
> I tried on an empty instance, I see the star now (so it's maybe a plugin override issue as you say), but I cannot click on it, nothing happens, the star stay empty (outlined in black, white inside)

It's probably the same issue as #2

**Comment by jajm** [comment]
Closing this one because #2 is fixed now
