### ISSUE TITLE
./cli install PHP Warning

### ISSUE THREAD

**Issue by landNull** [biblibre/kanboard-plugin-StarredProjects#10]
Installed this plugin using the command line like so..  
./cli plugin:install https://github.com/biblibre/kanboard-plugin-StarredProjects/archive/refs/heads/master.zip
Received this Warning
PHP Warning:  Use of undefined constant tls - assumed 'tls' (this will throw an Error in a future version of PHP) in /var/www/html/config.php on line 59
[critical] UpdateNotifier-master: Unable to load this plugin class: \Kanboard\Plugin\UpdateNotifier-master\Plugin

**Comment by jajm** [comment]
This error is not related to StarredProjects. The error message is about UpdateNotifier plugin.
Also there is a problem in your config file.
Closing
