### ISSUE TITLE
Starred Projects Not Working

### ISSUE THREAD

**Issue by aidedinertial** [biblibre/kanboard-plugin-StarredProjects#3]
## Description
The Starred Projects Plugin is not working for my installation of Kanboard. I am unable to "star" or "unstar" projects from the dshboard. See Kanboard configuration, below.

I installed the plugin using the Plugin Dashboard as administrator.

## Kanboard Configuration
```
Application version: 1.2.12
PHP version: 7.2.24-0ubuntu0.18.04.1
PHP SAPI: fpm-fcgi
HTTP Client: socket
OS version: Linux 4.15.0-72-generic
Database driver: mysql
Database version: 10.4.11-MariaDB-1:10.4.11+maria~bionic-log
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.79 Safari/537.36
```

## Browser Version
```
Google Chrome: Version 79.0.3945.79 (Official Build) (64-bit)
```

**Comment by jajm** [comment]
Have you tried with the latest version (`master` branch) of the plugin ?

**Comment by aidedinertial** [comment]
Thanks @jajm!

I installed the latest version manually (`master`, SHA1=`f8d1a02b`) and everything is working.
