### ISSUE TITLE
Show only StarredProjects in the ProjectSwitcher

### ISSUE THREAD

**Issue by TimoStahl** [biblibre/kanboard-plugin-StarredProjects#4]
I like the idea of preffered project, which could be accessed faster.

Maybe it would be a nice addion to show only starred project in the top menu bar.

![image](https://user-images.githubusercontent.com/1961634/75555331-504d4400-5a3c-11ea-9cdc-473f5b167636.png)

**Comment by jajm** [comment]
I agree it would be a great addition.
If you want to work on this, please submit a pull request, and I'll review it as soon as I can

**Comment by TimoStahl** [comment]
see PR #5 😃

**Comment by jajm** [comment]
Thanks !

I've been thinking about this. And I think a better solution to hiding all non-favorite projects, is to show favorite projects first and then the other ones. This way we can continue to use the project switcher to go to any project, but it's easier to switch to favorite projects.

I made small modifications on top of your branch to do that : https://github.com/biblibre/kanboard-plugin-StarredProjects/tree/show-favorite-projects-first-in-board-selector
Please tell me what you think about it.

**Comment by TimoStahl** [comment]
In our case, everybody has read access to every project but doesn't need them daily (in fast access). 
I have 20-30 projects in my top bar, but don't want to search for my important projects every time.

It would be possible to put them on top, but my preffered way would be to hide them. Maybe an option in the user settings could serve everybodies need.

**Comment by TimoStahl** [comment]
With the new hooks, the coding should be even better: https://github.com/kanboard/kanboard/pull/4425

**Comment by jajm** [comment]
> It would be possible to put them on top, but my preffered way would be to hide them. Maybe an option in the user settings could serve everybodies need.

I added a commit in my branch that does just that. Can you test it ?

**Comment by TimoStahl** [comment]
Very nice 😃

**Comment by TimoStahl** [comment]
The new hooks from https://github.com/kanboard/kanboard/pull/4425 were accepted, so this plugin doesn't need to overwrite any template file. It could be all done via hooks.

**Comment by jajm** [comment]
> The new hooks from [kanboard/kanboard#4425](https://github.com/kanboard/kanboard/pull/4425) were accepted, so this plugin doesn't need to overwrite any template file. It could be all done via hooks.

Nice.
I think I will merge it like that for now, and wait for a kanboard release before using the new hooks.

**Comment by jajm** [comment]
Closed by 9fabe928e592282162f94ffc47e597eb26ae7bca

I released a version 0.2.0 that includes it.

Thanks for your contribution!
