### ISSUE TITLE
Old version in Kanboard Plugin Directory

### ISSUE THREAD

**Issue by linkp** [biblibre/kanboard-plugin-StarredProjects#6]
According to this project's [Releases page](https://github.com/biblibre/kanboard-plugin-StarredProjects/releases), version 0.2.0 is the most recent. The Kanboard Plugin Directory still lists Starred Projects version 0.1.1, although no mention of the plugin appears on the [Kanboard website plugins page](https://kanboard.org/plugins.html).

Both symptoms appear to have the same solution of submitting a pull request to the [Kanboard Website repo](https://github.com/kanboard/website). The public listings are in the plugins.html file, and the plugin directory content is in the plugins.json file.

While I could submit pull requests for both myself, I expect they would have more credibility if they were submitted by someone directly connected to this project.

**Comment by jajm** [comment]
Thanks for the opening this issue.
I opened a pull request : https://github.com/kanboard/website/pull/251
