### ISSUE TITLE
stars do not display after update

### ISSUE THREAD

**Issue by elhamshoari** [biblibre/kanboard-plugin-StarredProjects#8]
after Updating kanboard the stars didn't display in screen, however my previous starred projects are shown with an star beside them.

**Comment by pmoule** [comment]
Comparable issue here. I am not able to star a project on kanboard's dashboard any longer after updating from 1.2.13. Kanboard version is 1.2.16. Starred projects are still visible in project selector. I can even choose to show starred projects only.

**Comment by jajm** [comment]
Do you have other plugins enabled ? Can you try to disable all other plugins and see if it works ?

I'm using v1.2.19 and was using v1.2.16 before that. Never had a problem with this plugin.

**Comment by pmoule** [comment]
Hi @jajm 
sorry for late reply and thanks for the hint. Removing previously installed plugins and re-adding them one by one fixed the issue.
