### ISSUE TITLE
Removed projects still in starred list (without title)

### ISSUE THREAD

**Issue by DeRuiterIndustrieleAutomatisering** [biblibre/kanboard-plugin-StarredProjects#9]
When i remove a starred project the entry without a title stays in the starred projects list and can't be removed

**Comment by onlygecko** [comment]
I can confirm this behavior, after removing ("deleting", not "closing") a project. 

![image](https://user-images.githubusercontent.com/3233376/119983350-54aa3900-bfc0-11eb-943e-e07606ba6fb9.png)
